# Generated by Django 6.1 on 2026-08-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_hash', models.CharField(max_length=255)),
                ('from_email', models.CharField(db_column='from', max_length=500)),
                ('subject', models.TextField()),
                ('workflow_processed_time', models.DateTimeField()),
                ('email_snippet', models.TextField(blank=True, null=True)),
                ('message_id', models.CharField(max_length=255)),
                ('email_received_time', models.DateTimeField()),
                ('category', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=50)),
                ('summary', models.TextField()),
            ],
            options={
                'db_table': 'processed_emails',
                'managed': False,
            },
        ),
    ]
